clear:
	@ rm -rf *.out

build:
	@ g++ heapsort_r.cpp heapsort.cpp utils.cpp -o heapsort_r.out
	@ g++ heapsort_r.cpp heapsort.cpp utils.cpp -o heapsort_r.out
	@ g++ heapsort_r.cpp heapsort.cpp utils.cpp -o heapsort_r.out

graphs:
	@ g++ graph_heapsort_r.cpp utils.cpp -o graph_heapsort_r.out -lpython3.9
	@ g++ graph_heapsort_r.cpp utils.cpp -o graph_heapsort_r.out -lpython3.9
	@ g++ graph_heapsort_r.cpp utils.cpp -o graph_heapsort_r.out -lpython3.9
	@ g++ graph_heapsort_r.cpp utils.cpp -o graph_heapsort_r.out -lpython3.9